### ISSUE TITLE
Realtime Database 

### ISSUE THREAD

**Issue by iamthenewking** [utkuce/syncwatch-web#16]
hi

Can you help me how you setup the Realtime Database ?

thanks

**Comment by utkuce** [comment]
Hello,
You can go to https://console.firebase.google.com/ and click "add project", then in that project select realtime database from the left side menu and click "create database"

**Comment by iamthenewking** [comment]
Thank you, but do i have to do anything after i created the database?

**Comment by iamthenewking** [comment]
![image](https://user-images.githubusercontent.com/7221308/152897786-c82abf86-13b0-4a99-aad6-9ca9b812ad37.png)


do I have to configure something here?


thanks

**Comment by utkuce** [comment]
Nothing needs to be done on that page, but the firebase credentials need to be copied into [room.ts](https://github.com/utkuce/syncwatch-web/blob/master/src/room.ts) before running the project. Credentials can be found by clicking the gear icon on the top left and going into the project settings. Then adding a web app.
Other than that it's a good idea to add some [firebase rules](https://firebase.google.com/docs/rules) for security. You can copy the contents of [rules.json](https://github.com/utkuce/syncwatch-web/blob/master/firebase_rules/rules.json)

**Comment by iamthenewking** [comment]
> Nothing needs to be done on that page, but the firebase credentials need to be copied into [room.ts](https://github.com/utkuce/syncwatch-web/blob/master/src/room.ts) before running the project. Credentials can be found by clicking the gear icon on the top left and going into the project settings. Then adding a web app. Other than that it's a good idea to add some [firebase rules](https://firebase.google.com/docs/rules) for security. You can copy the contents of [rules.json](https://github.com/utkuce/syncwatch-web/blob/master/firebase_rules/rules.json)

thank you . ill try that
